version: "2"
services:
  nuxt:
    image: "node:12.0"
    restart: unless-stopped
    volumes:
      - ./:/tmp/app/
    working_dir: /tmp/app/
    ports:
      - "3000:3000"
    command: bash -c "yarn && yarn dev"
    environment:
      HOST: 0.0.0.0
